version: "3.7"

services:
  pg:
    image: postgres:16-alpine
    environment:
      - POSTGRES_DB=cpm
      - POSTGRES_USER=cpm
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - ./temp/pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U cpm" ]
      interval: 30s
      timeout: 30s
      retries: 3
